apiVersion: v2
description: Reporting Legacy API
name: reporting-legacy-api
version: 1.0.0
appVersion: "1.0.5"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/reporting-legacy-api
maintainers:
  - name: Yevhen Kyriukha
    email: yevhen.kyriukha@modusbox.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: 1.0.0
  - name: reporting-crd
    repository: "file://../reporting-crd"
    tags:
      - reporting-crd
    version: 1.0.0

