apiVersion: v2
description: Reporting Legacy API
name: reporting-legacy-api
version: 2.0.4
appVersion: "11.0.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/reporting-legacy-api
maintainers:
  - name: Yevhen Kyriukha
    email: yevhen.kyriukha@modusbox.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: 2.0.0
  - name: reporting-k8s-templates
    alias: reporting-k8s-templates
    condition: install-templates
    repository: "https://mojaloop.github.io/reporting-k8s-templates"
    tags:
      - mojaloop
      - reporting-templates
    version: 1.1.5
