{{- $root := . -}}
{{- if .Values.wso2.identityServer.createSecrets -}}
{{- range $secretName, $secretEntry := .Values.wso2.identityServer.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ $root.Release.Namespace }}
data:
{{- range $k, $v := $secretEntry }}
  {{ $k }}: {{ $v | b64enc | quote }}
{{- end }}
{{- end }}
{{- end }}