apiVersion: v2
description: Reporting Events Processor
name: reporting-events-processor-svc
version: 3.1.0
appVersion: "3.1.0"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/reporting-events-processor-svc
maintainers:
  - name: Yevhen Kyriukha
    email: yevhen.kyriukha@modusbox.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: ">= 3.1.2"
