apiVersion: {{ include "common.capabilities.deployment.apiVersion" . }}
kind: Deployment
metadata:
  name: {{ template "common.names.fullname" . }}
  namespace: {{ .Release.Namespace | quote }}
  labels: {{- include "common.labels.standard" . | nindent 4 }}
    app.kubernetes.io/component: {{ template "common.names.chart" . }}
    {{- if .Values.commonLabels }}
    {{- include "common.tplvalues.render" ( dict "value" .Values.commonLabels "context" $ ) | nindent 4 }}
    {{- end }}
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "common.labels.matchLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ template "common.names.chart" . }}
  template:
    metadata:
      annotations: 
        checksum/config: {{ include (print $.Template.BasePath "/config.yaml") . | sha256sum }}
      {{- if .Values.podAnnotations }}
      {{- include "common.tplvalues.render" (dict "value" .Values.podAnnotations "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.metrics.enabled }}
        prometheus.io/port: "{{ .Values.service.internalPort }}"
        prometheus.io/scrape: "true"
      {{- end }}
      labels: {{- include "common.labels.standard" . | nindent 8 }}
        app.kubernetes.io/component: {{ template "common.names.chart" . }}
        app.kubernetes.io/version: {{ .Chart.Version }}
        {{- if .Values.podLabels }}
        {{- include "common.tplvalues.render" (dict "value" .Values.podLabels "context" $) | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ template "role-assignment-service.serviceAccountName" . }}
      {{- include "role-assignment-service.imagePullSecrets" . | nindent 6 }}
      {{- if .Values.hostAliases }}
      hostAliases: {{- include "common.tplvalues.render" (dict "value" .Values.hostAliases "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.affinity }}
      affinity: {{- include "common.tplvalues.render" ( dict "value" .Values.affinity "context" $) | nindent 8 }}
      {{- else }}
      affinity:
        podAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAffinityPreset "component" "role-assignment-service" "context" $) | nindent 10 }}
        podAntiAffinity: {{- include "common.affinities.pods" (dict "type" .Values.podAntiAffinityPreset "component" "role-assignment-service" "context" $) | nindent 10 }}
        nodeAffinity: {{- include "common.affinities.nodes" (dict "type" .Values.nodeAffinityPreset.type "key" .Values.nodeAffinityPreset.key "values" .Values.nodeAffinityPreset.values) | nindent 10 }}
      {{- end }}
      {{- if .Values.nodeSelector }}
      nodeSelector: {{- include "common.tplvalues.render" ( dict "value" .Values.nodeSelector "context" $) | nindent 8 }}
      {{- end }}
      {{- if .Values.tolerations }}
      tolerations: {{- include "common.tplvalues.render" (dict "value" .Values.tolerations "context" .) | nindent 8 }}
      {{- end }}
      {{- if .Values.priorityClassName }}
      priorityClassName: {{ .Values.priorityClassName | quote }}
      {{- end }}
      {{- if .Values.podSecurityContext.enabled }}
      securityContext: {{- omit .Values.podSecurityContext "enabled" | toYaml | nindent 8 }}
      {{- end }}
      initContainers:
        {{- if .Values.initContainers }}
          {{- include "common.tplvalues.render" (dict "value" .Values.initContainers "context" $) | nindent 8 }}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: {{ template "role-assignment-service.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.containerSecurityContext.enabled }}
          securityContext: {{- omit .Values.containerSecurityContext "enabled" | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.command "context" $) | nindent 12 }}
          {{- else if .Values.command }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.command "context" $) | nindent 12 }}
          {{- end }}
          {{- if .Values.diagnosticMode.enabled }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.diagnosticMode.args "context" $) | nindent 12 }}
          {{- else if .Values.args }}
          args: {{- include "common.tplvalues.render" (dict "value" .Values.args "context" $) | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.service.internalPort }}
          {{- if .Values.diagnosticMode.enabled }}
            - name: debug
              containerPort: {{ .Values.diagnosticMode.debug.internalPort }}
          {{- end }}
          {{- if .Values.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.readinessProbe.httpGet.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.livenessProbe.httpGet.path }}
              port: {{ .Values.service.internalPort }}
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            - name: {{ template "common.names.fullname" . }}-config-volume
              mountPath: /opt/role-assignment-service/config
          # env: {}

        {{- if .Values.sidecar.enabled }}
        - name: {{ .Chart.Name }}-sidecar
          image: "{{ .Values.sidecar.image.repository }}:{{ .Values.sidecar.image.tag }}"
          imagePullPolicy: {{ .Values.sidecar.image.pullPolicy }}
          {{- if .Values.sidecar.image.imagePullSecrets }}
          imagePullSecrets:
          {{ toYaml .Values.sidecar.image.imagePullSecrets | indent 10 }}
          {{- end }}
          command: {{- include "common.tplvalues.render" (dict "value" .Values.sidecar.image.command "context" $) | nindent 12 }}
          ports:
            - containerPort: {{ .Values.sidecar.service.internalPort }}
          {{- if .Values.sidecar.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ .Values.sidecar.readinessProbe.httpGet.path }}
              port: {{ .Values.sidecar.service.internalPort }}
            initialDelaySeconds: {{ .Values.sidecar.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.readinessProbe.periodSeconds }}
          {{- end }}
          {{- if .Values.sidecar.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ .Values.sidecar.livenessProbe.httpGet.path }}
              port: {{ .Values.sidecar.service.internalPort }}
            initialDelaySeconds: {{ .Values.sidecar.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.sidecar.livenessProbe.periodSeconds }}
          {{- end }}
          volumeMounts:
            - name: {{ template "common.names.fullname" . }}-sidecar-volume
              mountPath: /opt/event-sidecar/config
          env:
            - name: LOG_LEVEL
              value: {{ .Values.sidecar.config.log_level | quote }}
            - name: LOG_FILTER
              value: {{ .Values.sidecar.config.log_filter | quote }}
            - name: EVENT_SDK_LOG_FILTER
              value: {{ .Values.sidecar.config.event_log_filter | quote }}
            - name: EVENT_SDK_LOG_METADATA_ONLY
              value: {{ .Values.sidecar.config.event_log_metadata_only | quote }}
        {{- end }}
      volumes:
        - name: {{ template "common.names.fullname" . }}-config-volume
          configMap:
            name: {{ template "common.names.fullname" . }}-config
            items:
            - key: default.json
              path: default.json
        {{- if .Values.sidecar.enabled }}
        - name: {{ template "common.names.fullname" . }}-sidecar-volume
          configMap:
            name: {{ template "common.names.fullname" . }}-sidecar
            items:
            - key: default.json
              path: default.json
        {{- end }}
