## Installation
# helm upgrade bof ./mojaloop/bof --install

# Default values for bof.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keto:
    readURL: "http://keto-read:80"
    writeURL: "http://keto-write:80"

  rolePermOperator:
    mojaloopRole: {}
    mojaloopPermissionExclusion: {}
    apiSvc: {}

security-role-perm-operator-svc:
  enabled: true
