## Installation
# helm upgrade bof ./mojaloop/bof --install

# Default values for bof.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  keto:
    readURL: "http://keto-read:80"
    writeURL: "http://keto-write:80"
  wso2:
    identityServer:
      host: "wso2-identity-server.local"
      port: 9443
      userListURL: "http://wso2-identity-server.local:9443/scim2/Users"
      user: 'admin'
      secret:
        name: wso2-is-admin-creds
        key: password

  rolePermOperator:
    mojaloopRole: {}
    mojaloopPermissionExclusion: {}
    apiSvc: {}
  ## Currently setting the following to dummy values and we need to remove this dependency
  adminApiSvc:
    host: "dummy"
    port: 80

role-assignment-service:
  enabled: true
  ingress:
    enabled: true
    hostname: api-bof.local
    path: /proxy/iam(/|$)(.*)
    annotations:
      nginx.ingress.kubernetes.io/rewrite-target: /$2
  configFiles:
    default.json: {
        "ROLES_LIST": [
          "USER_ROLE_abc7a2fd-4acf-4547-a194-1673f63eb37c",
          "ADMIN_ROLE_6c1ec084-86d4-4915-ba81-6c59b87a65a6"
        ]
      }


security-role-perm-operator-svc:
  enabled: true
