## Installation
# helm upgrade bof ./mojaloop/bof --install 

# Default values for bof.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  adminApiSvc:
    host: "centralledger-service"
    port: 80
  keto:
    host: "keto"
    readPort: 4466
    writePort: 4467
  wso2:
    identityServer:
      host: "identity-server"
      port: 9443

role-assignment-service:
  enabled: true

reporting-hub-bop-shell:
  enabled: true

security-role-perm-operator-svc:
  enabled: true

security-hub-bop-kratos-ui:
  enabled: true