apiVersion: v2
description: Reporting API service
name: reporting-hub-bop-api-svc
version: 1.0.1
appVersion: "1.0.31"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/reporting-hub-bop-api-svc
maintainers:
  - name: Yevhen Kyriukha
    email: yevhen.kyriukha@modusbox.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: 2.0.0
