global:
  adminApiSvc:
    host: "centralledger-service"
    port: 80
  settlementSvc:
    host: "centralsettlement-service"
    port: 80
  keto:
    readURL: "http://keto-read:80"
  reportingDB:
    host: mysqldb
    port: 3306
    user: central_ledger
    database: central_ledger
    # secret: {}
    secret:
      name: mysqldb
      key: mysql-password
  reportingEventsDB:
    host: reporting-events-db
    port: 27017
    user: finance_portal
    database: finance_portal
    # secret: {}
    secret:
      name: reporting-events-db
      key: mongodb-passwords
  ## The following can be used if using mongodb operator deployment
  # reportingEventsDB:
  #   host: reporting-events-db-svc
  #   port: 27017
  #   user: finance_portal
  #   database: finance_portal
  #   secret:
  #     name: reporting-events-db-finance-portal-finance-portal
  #     key: password
  kafka:
    host: test1-kafka-headless
    port: 9092
    topic: topic-event
  rolePermOperator:
    apiSvc: {}
  keycloak:
    url: 'http://keycloak:8080'
    user: 'admin'
    password: ''
    # secret:
    #   name: 'keycloak-secret'
    #   key: 'password'
    realm: 'master'


rbacTests:
  enabled: false

reportTests:
  enabled: false

role-assignment-service:
  enabled: false

reporting-hub-bop-api-svc:
  enabled: false

reporting-legacy-api:
  enabled: false

reporting-events-processor-svc:
  enabled: false

reporting-hub-bop-experience-api-svc:
  enabled: false

reporting-hub-bop-shell:
  enabled: false

reporting-hub-bop-role-ui:
  enabled: false

reporting-hub-bop-trx-ui:
  enabled: false

reporting-hub-bop-positions-ui:
  enabled: false

reporting-hub-bop-settlements-ui:
  enabled: false

reporting-aggregator-svc:
  enabled: true
