apiVersion: v2
description: Reporting Aggregator Service
name: reporting-aggregator-svc
version: 1.0.6
appVersion: "0.0.9"
home: http://mojaloop.io
icon: http://mojaloop.io/images/logo.png
sources:
  - https://github.com/mojaloop/mojaloop
  - https://github.com/mojaloop/helm
  - https://github.com/mojaloop/reporting-aggregator-svc
maintainers:
  - name: Vijay Kumar Guthi
    email: vijaya.guthi@infitx.com
dependencies:
  - name: common
    repository: "file://../common"
    tags:
      - moja-common
    version: ">= 3.1.5"
